version: '3'

tasks:

  clean:
    cmds:
      - |
        rm mlflow.db
        rm -rf mlruns

  mlflow-start:
    cmds:
      - mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root mlruns/ --host 0.0.0.0 --port 5000
