version: '3'

tasks:

  clean:
    cmds:
      - |
        rm -f mflow.db
        rm -rf mlruns
        rm -rf outputs

  mlflow-start:
    cmds:
      - mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root mlruns/ --host 0.0.0.0 --port 5000
