version: '3'

tasks:

  clean:
    cmds:
      - |
        rm mlflow.db
        rm -rf mlruns

  init:
    cmds:
      - |
        poetry config virtualenvs.path .virtualenv
        poetry env use python3.8
        poetry install
